spring:
  application:
    name: "rempms-configuration-service"
  profiles:
    active: git
  cloud:
    config:
      server:
        #        native:
        #        search-locations: "classpath:/config"
        #        search-locations: "file:///C://Users//User//Documents//config"
        git:
          uri: "https://github.com/pixel-mind-solutions-group/rempms-config.git"
          default-label: main
          clone-on-start: true
          force-pull: true
          timeout: 3
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      enabled: true
      application: ${spring.application.name}

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

logging:
  level:
    org.springframework.cloud.bus: DEBUG

server:
  port: 8071